name: Docker

on:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc*'

env:
  IMAGETAG: ${GITHUB_REF}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Test Docker Build
        run: docker build .
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # @v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get tag metadata
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # @v5.0.0
        with:
          images: |
            filecoin/sentinel-locations
          tags: |
            type=semver,pattern={{version}}
      - name: Push to Docker Hub
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # @v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
